// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:anime_flow/models/play/play_history.dart';
import 'package:anime_flow/models/play/play_position.dart';
import 'package:anime_flow/models/search/search_history_module.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PlayHistoryAdapter());
    registerAdapter(PlayPositionAdapter());
    registerAdapter(SearchHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PlayHistoryAdapter());
    registerAdapter(PlayPositionAdapter());
    registerAdapter(SearchHistoryAdapter());
  }
}
